name: Generate Animation

on:
  schedule: # run automatically every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

# run on every push on the master branch
push:
  branches:
  - main

jobs:
  generate:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Snake Animation
      - name: generate github-contribution-grid-snake.svg
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}